# Assignment 3

**Please follow the instructions. Do not add new cell! Write your code in designated areas.**

In [32]:
import datetime
import socket

# Get local time
local_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Get computer ID or hostname
computer_id = socket.gethostname()

# Print output with local time and computer ID
print('Assignment 1 & 2: Solutions by Ethan') # Please change your name here
print('Local Time:', local_time)
print('Computer ID:', computer_id)

Assignment 1 & 2: Solutions by Ethan
Local Time: 2023-07-03 16:30:30
Computer ID: hcm-Thong


## NumPy

1. Create a 2D numpy array of size 4x5 with random integers between 1 and 10. Find the maximum value of the entire array. 


In [5]:
## Your code here down
import numpy as np

np_array = np.full((4,5), np.random.randint(0,100,(4,5)))

print(np_array)

max_value = np.max(np_array)

print(max_value)
# print(mean)
#print(std) and so on
## Your code here up

[[ 1 70 79 93 28]
 [68 90 20 66 22]
 [38 15 60 37 12]
 [28 80 29 21  2]]
93


2. Create a 1D numpy array of size 20 with random floats between 0 and 1. Reshape the array into a 4x5 matrix. Compute the mean of each row.

In [6]:
## Your code here down
# Create a 1D numpy array with a size of 20, random floats between 0 and 1

float_array = np.random.random(20)

print(float_array)

# reshape the array into 4x5 maxtrix
new_float_array = float_array.reshape(4,5)

print(new_float_array)

#  compute the mean of each row
mean_array = np.mean(new_float_array, axis = 1)

print(mean_array)
## Your code here up

[0.77861066 0.67635867 0.39877557 0.33968349 0.34431287 0.11003851
 0.99479453 0.41722747 0.20762911 0.69411139 0.20523714 0.58161682
 0.24053631 0.34346575 0.7722128  0.92147846 0.80325319 0.66953057
 0.20911576 0.50826078]
[[0.77861066 0.67635867 0.39877557 0.33968349 0.34431287]
 [0.11003851 0.99479453 0.41722747 0.20762911 0.69411139]
 [0.20523714 0.58161682 0.24053631 0.34346575 0.7722128 ]
 [0.92147846 0.80325319 0.66953057 0.20911576 0.50826078]]
[0.50754825 0.4847602  0.42861377 0.62232775]


3. Create a 2D numpy array of size 5x5 with random integers between 1 and 100. Compute standard deviation of each column.

In [7]:
## Your code here down
# create a 2D numpy array of size 5x5 with random values between 1 and 100
int_array = np.random.randint(100, size=(5,5))

print(int_array)

# compute the standard deviation of each column
std_int_array = np.std(int_array, axis = 0)

print(std_int_array)

## Your code here up

[[75 33 36 35 31]
 [65 38  2 84 78]
 [65 29 30 64 16]
 [40 18 28 93 47]
 [78 89 75 30 60]]
[13.36562756 24.69493875 23.49808503 25.29347742 21.65733132]


4. Create a 1D numpy array of size 15 with random floats between -10 and 10. Replace all negative values with their absolute values.

In [8]:
## Your code here down
# create a 1D numpy array of size 15 with random floats between -10 and 10
array_4 = np.random.uniform(low = -10, high = 10, size = 15)

print(array_4)

# replace all negative values with their absolute values
abs_array_4 = np.absolute(array_4)

print(abs_array_4)
## Your code here up

[-6.79763561 -8.80712548 -0.78765374 -3.27255948  4.92780482  5.23920691
 -1.05936858  8.7943404   6.98654396 -8.57729743  1.31711573 -0.2731469
  3.41404123  6.53233264  2.85549066]
[6.79763561 8.80712548 0.78765374 3.27255948 4.92780482 5.23920691
 1.05936858 8.7943404  6.98654396 8.57729743 1.31711573 0.2731469
 3.41404123 6.53233264 2.85549066]


5. Create a 2D numpy array of size 3x4 with random integers between 1 and 100. Calculate the sum of all elements in the array.

In [9]:
## Your code here down
# create a 2D numpy array of size 3x4 with random integers between 0 and 100
array_5 = np.random.randint(100, size = (3,4))

print(array_5)

# calculate the sum of all elements in the array
sum_array_5 = np.sum(array_5)

print(sum_array_5)
## Your code here up

[[25 75 15 96]
 [15 71 55 42]
 [87 78 59 71]]
689


7. Create a 2D numpy array of size 4x6 with random floats between 0 and 1. Normalize each column by subtracting the column mean and dividing by the column standard deviation.

In [10]:
## Your code here down
# create a 2D numpy array of size 4x6 with random floats between 0 and 1
array_7 = np.random.random(size = (4, 6))

print(array_7)

# calculate the mean of each column in the array
mean_array_7 = np.mean(array_7, axis = 0)

print(mean_array_7)
# calculate the standard deviation of each column in the array
std_array_7 = np.std(array_7, axis = 0)

print(std_array_7)
# normalize the array
norm_array_7 = np.subtract(mean_array_7, std_array_7)

print(norm_array_7)
## Your code here up

[[0.23472119 0.5524112  0.31828613 0.04086224 0.9248358  0.15712195]
 [0.04440009 0.51969598 0.57826895 0.17743831 0.65047914 0.3244914 ]
 [0.70349246 0.00391122 0.27810459 0.0265586  0.70748265 0.43383129]
 [0.29800768 0.73932917 0.61092865 0.7743871  0.11821317 0.61994677]]
[0.32015535 0.45383689 0.44639708 0.25481156 0.60025269 0.38384786]
[0.2401967  0.27294379 0.14932816 0.30570373 0.29653721 0.1682029 ]
[ 0.07995865  0.1808931   0.29706892 -0.05089217  0.30371548  0.21564495]


8. Create a 2D numpy array of size 10x10 with random integers between 1 and 100. Replace all values greater than 50 with 1 and all other values with 0.

In [32]:
## Your code here down
# create a 2D numpy array of size 10x10 with random integers between 0 and 100
array_8 = np.random.randint(100, size = (10,10))

print(array_8)
# replace the values
array_8[array_8 <= 50] = 0

array_8[array_8 > 50] = 1

print(array_8)
## Your code here up

[[80 55 10 29 64 17 58 39 76  1]
 [ 5 78  8 72 87 86 60  4 73 33]
 [22 17 94 79 57 67 15 12 26 25]
 [33 43 70 60 98 80 82  7 92 16]
 [ 9 72 38 95 92 36 24 43 96 23]
 [16 25 18 19 45 29 88  3  0  2]
 [62 89 60 26 79 55 11  8 69 13]
 [99 83 28  5 98 11 72 90 48 62]
 [22 37 87 43 17 66 85  4 66 92]
 [96 26 50 93 82 61 13 28 74  4]]
[[1 1 0 0 1 0 1 0 1 0]
 [0 1 0 1 1 1 1 0 1 0]
 [0 0 1 1 1 1 0 0 0 0]
 [0 0 1 1 1 1 1 0 1 0]
 [0 1 0 1 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 1 1 0 1 1 0 0 1 0]
 [1 1 0 0 1 0 1 1 0 1]
 [0 0 1 0 0 1 1 0 1 1]
 [1 0 0 1 1 1 0 0 1 0]]


9. Create a 1D numpy array of size 50 with random floats between 0 and 1. Find the number of elements greater than 0.5.

In [11]:
## Your code here down
# create a 2D numpy array of size 50 with random floats between 0 and 1.
array_9 = np.random.random(50)

print(array_9)

count = (array_9 > 0.5).sum()

print(count)
## Your code here up

[0.16767814 0.74091308 0.01069379 0.05305296 0.97584872 0.12894327
 0.64664219 0.59208509 0.5713611  0.70537266 0.03606965 0.31104431
 0.40995538 0.93630159 0.90323754 0.52766912 0.82662791 0.30651482
 0.91101231 0.62951915 0.32530939 0.39442007 0.92270468 0.2392288
 0.22120074 0.72676431 0.6322354  0.19032692 0.74641049 0.51625252
 0.26189614 0.77952561 0.1219032  0.74736053 0.05780462 0.50230848
 0.56027374 0.91422506 0.84745807 0.11944818 0.09898053 0.70995303
 0.7401145  0.26616647 0.79730977 0.62577281 0.29986687 0.86568945
 0.89142329 0.15101453]
29


10. Create a 2D numpy array of size 5x5 with random floats between -1 and 1. Find the absolute difference between the maximum and minimum values in each row.

In [12]:
## Your code here down
array_10 = np.random.uniform(low = -1, high = 1, size = (4,5))

print(array_10)

max_array_10 = np.max(array_10, axis = 1)

print(max_array_10)

min_array_10 = np.min(array_10, axis = 1)

print(min_array_10)

abs_diff_array = np.subtract(max_array_10, min_array_10)

print(abs_diff_array)
## Your code here up

[[ 0.85456926 -0.15904256  0.10309835 -0.07447005  0.11147615]
 [-0.21208667  0.87654164 -0.7686708   0.19353272 -0.01248975]
 [-0.07488449 -0.99418495 -0.40746036 -0.47692419 -0.44104077]
 [-0.97281644 -0.74350858  0.30473505  0.41704206  0.45653665]]
[ 0.85456926  0.87654164 -0.07488449  0.45653665]
[-0.15904256 -0.7686708  -0.99418495 -0.97281644]
[1.01361183 1.64521244 0.91930046 1.42935309]


## Pandas

Please refer the dataframe (farm data) we have created in the training. Please copy that cell and paste it below before starting this part. 

In [14]:
import random
import pandas as pd

# Define the range for longitude and latitude
lon_range = (-105, -100)
lat_range = (50, 52)

# Define the list of soil types
soil_types = ['black', 'gray', 'dark brown', 'brown', None]

# Create an empty list to store the farms
farms = []

# Generate 40 farms
for i in range(40):
    farm = {
        'farm_name': f'Farm {i+1}', # f is formated string
        'farm_lon': round(random.uniform(lon_range[0], lon_range[1]), 2), # random lon with 2 decimal points
        'farm_lat': round(random.uniform(lat_range[0], lat_range[1]), 2), # rantom lat with 2 decimal points
        'temperature': round(random.uniform(18, 25), 1), #random temp with 1 decimal points
        'precipitation': round(random.uniform(20, 50), 1), # random prec with 1 decimal points
        'soil_type': random.choice(soil_types) # random soil types from above list
    }
    farms.append(farm)

In [15]:
df = pd.DataFrame(farms)# your code here

1. Select the rows where the temperature is above 20 degrees Celsius.

In [44]:
## Your code here down
df[df['temperature'] > 20]

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
0     Farm 1   -103.75     51.06         23.0           41.8  dark brown
2     Farm 3   -103.89     51.52         24.2           39.8  dark brown
4     Farm 5   -103.24     50.19         20.4           28.6       brown
5     Farm 6   -100.38     51.25         21.3           30.7        gray
6     Farm 7   -104.62     51.98         23.3           41.3  dark brown
7     Farm 8   -103.85     50.86         22.6           38.1        None
8     Farm 9   -103.86     51.08         22.3           31.3       brown
9    Farm 10   -104.67     51.45         24.8           32.1        gray
10   Farm 11   -100.42     51.76         22.1           24.9        gray
11   Farm 12   -104.60     51.43         22.4           41.0        gray
12   Farm 13   -101.07     50.84         23.7           24.4  dark brown
14   Farm 15   -100.62     51.44         22.7           21.2  dark brown
15   Farm 16   -100.19     51.62         24.6           34.1       brown
16   Farm 17   -101.18     50.72         23.7           25.3       brown
17   Farm 18   -103.06     50.79         20.1           27.0        gray
18   Farm 19   -100.02     50.60         23.3           48.2        gray
19   Farm 20   -103.80     51.88         23.8           45.3       black
20   Farm 21   -102.69     51.95         21.1           30.1        None
21   Farm 22   -104.76     51.76         20.4           43.8       brown
22   Farm 23   -103.11     50.79         20.7           39.3        gray
24   Farm 25   -101.53     50.42         24.7           42.2        gray
26   Farm 27   -103.04     51.72         24.4           25.2  dark brown
28   Farm 29   -100.99     51.05         21.6           38.2        None
30   Farm 31   -104.88     51.72         20.8           36.3        None
31   Farm 32   -103.16     50.25         21.4           47.6        gray
32   Farm 33   -100.86     51.69         24.2           24.0       black
33   Farm 34   -102.71     51.69         24.9           40.0  dark brown
35   Farm 36   -103.26     50.83         22.4           43.4       brown
36   Farm 37   -104.62     51.73         20.6           46.6  dark brown
37   Farm 38   -103.40     50.29         22.3           20.8        None
38   Farm 39   -101.03     50.07         20.8           28.2        None
39   Farm 40   -100.27     51.11         21.2           37.8        gray

2. Sort the DataFrame by precipitation in descending order.

In [16]:
## Your code here down
df.sort_values('precipitation', ascending=False)

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
13   Farm 14   -104.67     51.50         20.0           49.9       brown
29   Farm 30   -103.85     50.74         21.9           48.5        gray
8     Farm 9   -101.59     50.68         24.9           48.3       black
30   Farm 31   -101.58     51.21         22.1           46.4       brown
7     Farm 8   -102.90     51.02         19.8           46.4       black
17   Farm 18   -104.61     50.65         24.2           45.1        gray
37   Farm 38   -103.09     50.02         20.1           45.0        None
9    Farm 10   -103.72     50.88         24.7           44.8       black
33   Farm 34   -103.22     51.42         23.0           44.4        None
25   Farm 26   -101.64     51.83         21.2           41.0        None
15   Farm 16   -103.01     51.57         22.2           39.1        gray
2     Farm 3   -100.12     50.37         22.5           36.0       black
31   Farm 32   -101.84     51.44         22.7           34.8       black
19   Farm 20   -104.61     51.86         19.5           33.5       brown
32   Farm 33   -104.34     51.47         19.3           33.3       black
4     Farm 5   -104.30     51.75         22.0           32.9        gray
26   Farm 27   -104.47     50.16         18.1           30.7       black
10   Farm 11   -100.79     51.89         22.0           30.3  dark brown
6     Farm 7   -101.21     51.28         18.4           29.2        gray
23   Farm 24   -102.84     51.66         20.8           28.9        None
5     Farm 6   -100.51     51.65         22.9           28.9        gray
14   Farm 15   -101.75     51.35         24.9           28.6       brown
11   Farm 12   -100.81     51.15         20.5           28.2  dark brown
22   Farm 23   -102.86     51.92         18.4           28.0  dark brown
39   Farm 40   -101.65     50.84         18.5           26.4  dark brown
24   Farm 25   -104.67     51.92         24.5           26.2       black
36   Farm 37   -102.27     50.32         18.5           24.8  dark brown
20   Farm 21   -101.30     51.48         23.1           24.6       black
28   Farm 29   -104.46     50.37         23.8           24.4  dark brown
38   Farm 39   -102.73     50.83         24.8           24.4  dark brown
34   Farm 35   -100.21     50.10         21.2           24.0        None
16   Farm 17   -103.08     50.56         23.0           23.6  dark brown
12   Farm 13   -100.15     51.32         20.6           22.3        None
18   Farm 19   -101.53     51.81         18.4           22.2       brown
1     Farm 2   -102.68     50.59         19.8           21.9       black
21   Farm 22   -104.79     50.25         19.6           21.7        None
27   Farm 28   -100.14     50.19         20.0           21.6  dark brown
35   Farm 36   -104.32     51.91         21.2           20.8        gray
0     Farm 1   -101.47     51.69         18.8           20.8        gray
3     Farm 4   -100.19     50.81         18.5           20.0        None

3. Filter the DataFrame to include only the farms located within latitude (51.15 & 51.00) range.

In [17]:
## Your code here down
df.loc[(df['farm_lat'] >= 51.00) & 
       (df['farm_lat'] <= 51.15)]

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
7     Farm 8   -102.90     51.02         19.8           46.4       black
11   Farm 12   -100.81     51.15         20.5           28.2  dark brown

 4. Calculate the standard deviation of precipitation for each soil type.

In [18]:
## Your code here down
df.loc[(df['soil_type'] == 'dark brown')]['precipitation'].std()

df.loc[(df['soil_type'] == 'brown')]['precipitation'].std()

df.loc[(df['soil_type'] == 'gray')]['precipitation'].std()

df.loc[(df['soil_type'] == 'black')]['precipitation'].std()

df.loc[(df['soil_type'].isnull())]['precipitation'].std()
## Your code here up

10.77091818608927

5. Calculate the cumulative sum of precipitation for each soil type.

In [19]:
## Your code here down
df.loc[(df['soil_type'] == 'dark brown')]['precipitation'].sum()

df.loc[(df['soil_type'] == 'brown')]['precipitation'].sum()

df.loc[(df['soil_type'] == 'gray')]['precipitation'].sum()

df.loc[(df['soil_type'] == 'black')]['precipitation'].sum()

df.loc[(df['soil_type'].isnull())]['precipitation'].sum()

## Your code here up

247.3

6. Determine the top 3 farms with the highest average temperature.

In [20]:
## Your code here down

df.sort_values('temperature',ascending=False).head(3)

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation   soil_type
14   Farm 15   -101.75     51.35         24.9           28.6       brown
8     Farm 9   -101.59     50.68         24.9           48.3       black
38   Farm 39   -102.73     50.83         24.8           24.4  dark brown

7. Find famrs in each soil type that have the highest temperature.

In [21]:
## Your code here down
df.loc[(df['soil_type'] == 'dark brown')].sort_values('temperature', ascending=False).head(1)

df.loc[(df['soil_type'] == 'brown')].sort_values('temperature', ascending=False).head(1)

df.loc[(df['soil_type'] == 'gray')].sort_values('temperature', ascending=False).head(1)

df.loc[(df['soil_type'] == 'black')].sort_values('temperature', ascending=False).head(1)

df.loc[(df['soil_type'].isnull())].sort_values('temperature', ascending=False).head(1)

## Your code here up

farm_name  farm_lon  farm_lat  temperature  precipitation soil_type
33   Farm 34   -103.22     51.42         23.0           44.4      None

8. Create new column 'percentage_tot_prec' and add the percentage contribution of each farm's precipitation (relative to total precipitation) to the column.

In [22]:
## Your code here down
percentage_tot_prec = []

total_prec = df['precipitation'].sum()

print(total_prec)

for i in range(len(df)):
    percentage_tot_prec.append((df.loc[i,'precipitation'] / total_prec))

df['percentage_tot_prec'] = percentage_tot_prec

## Your code here up

1271.9


9. Create a new column called "precipitation_rank" that ranks the farms based on their precipitation in ascending order, with ties being assigned the same rank.

In [23]:
## Your code here down
precipitation_rank = []

df.sort_values('precipitation', inplace=True)

len = len(df)

for i in range(len):
    precipitation_rank.append(len-i)
    
    print(precipitation_rank)

df['precipitation_rank'] = precipitation_rank

## Your code here up

[40]
[40, 39]
[40, 39, 38]
[40, 39, 38, 37]
[40, 39, 38, 37, 36]
[40, 39, 38, 37, 36, 35]
[40, 39, 38, 37, 36, 35, 34]
[40, 39, 38, 37, 36, 35, 34, 33]
[40, 39, 38, 37, 36, 35, 34, 33, 32]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20]
[40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27

10. Normalize the temperature column to a range between 0 and 1 for each farm.

In [30]:
## Your code here down
df['temperature'] = (df['temperature']-df['temperature'].min()) / (df['temperature'].max()-df['temperature'].min())


## Your code here up